s/DailySessionType\.Rest/DailySessionType.Recovery/g
s/DailySessionType\.SkillDevelopment/DailySessionType.SkillsOnly/g
s/DailySessionType\.PhysicalConditioning/DailySessionType.FitnessOnly/g
s/DailySessionType\.TacticalTraining/DailySessionType.Tactical/g
s/DailySessionType\.LightTraining/DailySessionType.Supplementary/g
s/DailySessionType\.ActiveRecovery/DailySessionType.Recovery/g
s/TrainingComponentType\.ActiveRecovery/TrainingComponentType.Recovery/g
s/TrainingComponentType\.Mobility/TrainingComponentType.Recovery/g
s/TrainingComponentType\.Regeneration/TrainingComponentType.Recovery/g
s/TrainingComponentType\.TacticalWork/TrainingComponentType.Tactical/g
s/TrainingComponentType\.SkillDrills/TrainingComponentType.Skills/g
s/TrainingComponentType\.LightSkills/TrainingComponentType.Skills/g
s/TrainingComponentType\.MatchSimulation/TrainingComponentType.Tactical/g
s/TrainingComponentType\.WarmUp/TrainingComponentType.Skills/g
s/TrainingComponentType\.TechnicalSkills/TrainingComponentType.Skills/g
s/TrainingComponentType\.StrengthTraining/TrainingComponentType.Fitness/g
s/TrainingComponentType\.SpeedWork/TrainingComponentType.Fitness/g
s/TrainingComponentType\.GameUnderstanding/TrainingComponentType.Tactical/g
s/TrainingComponentType\.Cardio/TrainingComponentType.Fitness/g
s/TrainingComponentType\.Flexibility/TrainingComponentType.Recovery/g
s/player\.Condition/player.Stamina/g
s/\.Role)/\.Role.ToString())/g
