name: Static Heuristic Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: python -m pip install pandas
      - name: Run static scan
        run: python Tools/ci/static_scan.py --repo-root . --out static_scan_report.csv
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: static-scan-report
          path: static_scan_report.csv
