name: Unity CI (Login-based)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  unity-tests:
    name: EditMode tests (Unity 6000.0.54f1)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-Unity-6000.0.54f1-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-Unity-6000.0.54f1-

      - name: Run EditMode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }} # leave empty or omit for Personal
        with:
          unityVersion: 6000.0.54f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: editmode
          artifactsPath: artifacts
          checkName: "Unity EditMode Tests"
          coverageOptions: "generateAdditionalMetrics;generateHtmlReport;generateBadge;assemblyFilters:+Assembly-CSharp"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unity-editmode-results
          path: artifacts
